"""Step 0: check the local environment and detect the external data disk.

This script performs only the environment/storage bootstrap for the flood
research pipeline. It does not download data and does not launch training.
"""

from __future__ import annotations

import argparse
import ctypes
import json
import os
import platform
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


DISK_LABEL = "ESD-USB"
PROJECT_DIR_NAME = "flood_research"


@dataclass(frozen=True)
class VolumeInfo:
    root: Path
    label: str
    filesystem: str | None = None


def _run_command(command: list[str]) -> dict[str, object]:
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return {
            "available": False,
            "command": command,
            "returncode": None,
            "stdout": "",
            "stderr": "command not found",
        }

    return {
        "available": completed.returncode == 0,
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }


def _detect_windows_volume(label: str) -> VolumeInfo | None:
    kernel32 = ctypes.windll.kernel32
    get_volume_information = kernel32.GetVolumeInformationW

    for code in range(ord("A"), ord("Z") + 1):
        root = f"{chr(code)}:\\"
        if not os.path.exists(root):
            continue

        volume_name = ctypes.create_unicode_buffer(261)
        fs_name = ctypes.create_unicode_buffer(261)
        serial_number = ctypes.c_ulong()
        max_component_len = ctypes.c_ulong()
        file_system_flags = ctypes.c_ulong()

        ok = get_volume_information(
            ctypes.c_wchar_p(root),
            volume_name,
            len(volume_name),
            ctypes.byref(serial_number),
            ctypes.byref(max_component_len),
            ctypes.byref(file_system_flags),
            fs_name,
            len(fs_name),
        )
        if not ok:
            continue

        if volume_name.value.casefold() == label.casefold():
            return VolumeInfo(
                root=Path(root),
                label=volume_name.value,
                filesystem=fs_name.value or None,
            )

    return None


def _detect_unix_volume(label: str) -> VolumeInfo | None:
    user = os.environ.get("USER") or os.environ.get("USERNAME") or ""
    candidates = []
    if platform.system() == "Darwin":
        candidates.append(Path("/Volumes") / label)
    else:
        if user:
            candidates.extend(
                [
                    Path("/media") / user / label,
                    Path("/run/media") / user / label,
                ]
            )
        candidates.extend([Path("/mnt") / label, Path("/media") / label])

    for candidate in candidates:
        if candidate.exists() and candidate.is_dir():
            return VolumeInfo(root=candidate, label=label)

    return None


def detect_external_disk(label: str = DISK_LABEL) -> VolumeInfo | None:
    if platform.system() == "Windows":
        return _detect_windows_volume(label)
    return _detect_unix_volume(label)


def _format_path(path: Path) -> str:
    return str(path).replace("\\", "/")


def _bytes_to_gb(value: int) -> float:
    return round(value / 1_000_000_000, 2)


def _bytes_to_gib(value: int) -> float:
    return round(value / (1024**3), 2)


def build_external_dirs(project_root: Path) -> list[Path]:
    return [
        project_root,
        project_root / "data" / "raw" / "sen1floods11",
        project_root / "data" / "processed" / "sen1floods11",
        project_root / "reports",
        project_root / "logs",
        project_root / "checkpoints",
    ]


def write_sen1_config(repo_root: Path, project_root: Path, disk_root: Path) -> Path:
    config_path = repo_root / "configs" / "sen1floods11.yaml"
    if config_path.exists():
        return config_path

    config_path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Generated by scripts/00_check_environment.py.
# This file stores detected paths only; no download has been performed.
external_disk_label: "{DISK_LABEL}"
external_disk_path: "{_format_path(disk_root)}"
project_root: "{_format_path(project_root)}"

raw:
  sen1floods11: "{_format_path(project_root / "data" / "raw" / "sen1floods11")}"

processed:
  sen1floods11: "{_format_path(project_root / "data" / "processed" / "sen1floods11")}"

reports: "{_format_path(project_root / "reports")}"
logs: "{_format_path(project_root / "logs")}"
checkpoints: "{_format_path(project_root / "checkpoints")}"

pipeline:
  current_step: 0
  next_step_allowed: false
"""
    config_path.write_text(text, encoding="utf-8")
    return config_path


def build_report(
    *,
    status: str,
    generated_at: str,
    repo_root: Path,
    volume: VolumeInfo | None,
    project_root: Path | None,
    created_dirs: list[Path],
    generated_files: list[Path],
    python_info: dict[str, object],
    pip_info: dict[str, object],
    conda_info: dict[str, object],
    disk_usage: shutil._ntuple_diskusage | None,
    warnings: list[str],
    dry_run: bool,
) -> str:
    lines = [
        "# STEP 0 - Environment report",
        "",
        "## Summary",
        f"- Status: `{status}`",
        f"- Generated at: `{generated_at}`",
        f"- Dry run: `{str(dry_run).lower()}`",
        f"- Local repo root: `{_format_path(repo_root)}`",
        "- Next step allowed: `false`",
        "",
        "## Environment",
        f"- Python executable: `{sys.executable}`",
        f"- Python version: `{python_info['version']}`",
        f"- pip: `{pip_info.get('stdout') or pip_info.get('stderr')}`",
        f"- conda: `{conda_info.get('stdout') or conda_info.get('stderr')}`",
        "",
        "## External disk",
    ]

    if volume is None:
        lines.extend(
            [
                f"- Required label: `{DISK_LABEL}`",
                "- Detection result: `not found`",
            ]
        )
    else:
        free_gb = _bytes_to_gb(disk_usage.free) if disk_usage else None
        free_gib = _bytes_to_gib(disk_usage.free) if disk_usage else None
        total_gb = _bytes_to_gb(disk_usage.total) if disk_usage else None
        lines.extend(
            [
                f"- Detected label: `{volume.label}`",
                f"- Disk path: `{_format_path(volume.root)}`",
                f"- Filesystem: `{volume.filesystem or 'unknown'}`",
                f"- Project storage root: `{_format_path(project_root)}`",
                f"- Total space: `{total_gb} GB`",
                f"- Free space: `{free_gb} GB` (`{free_gib} GiB`)",
            ]
        )

    lines.extend(["", "## Directories"])
    if created_dirs:
        lines.extend(f"- `{_format_path(path)}`" for path in created_dirs)
    else:
        lines.append("- None")

    lines.extend(["", "## Generated files"])
    if generated_files:
        lines.extend(f"- `{_format_path(path)}`" for path in generated_files)
    else:
        lines.append("- None")

    lines.extend(["", "## Problems detected"])
    if warnings:
        lines.extend(f"- {warning}" for warning in warnings)
    else:
        lines.append("- None")

    lines.extend(
        [
            "",
            "## Decisions to validate",
            "- Confirm that the detected external disk is the intended storage target.",
            "- Confirm that the available free space is sufficient before Step 1.",
            "- Confirm whether FAT32 is acceptable if large files are expected.",
            "",
            "## Proposed next step",
            "Step 1 can only start after human validation. It will document and download Sen1Floods11 into the external raw data directory.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Check only; do not create files or directories.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Local repository root.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    generated_at = datetime.now().isoformat(timespec="seconds")
    volume = detect_external_disk(DISK_LABEL)

    python_info = {"version": platform.python_version(), "executable": sys.executable}
    pip_info = _run_command([sys.executable, "-m", "pip", "--version"])
    conda_info = _run_command(["conda", "--version"])

    warnings: list[str] = []
    if not pip_info["available"]:
        warnings.append("pip was not available through the active Python interpreter.")
    if not conda_info["available"]:
        warnings.append("conda was not found. This is not blocking because pip is available.")

    if volume is None:
        warnings.append(f"External disk with label {DISK_LABEL!r} was not detected.")
        status = "blocked"
        project_root = None
        disk_usage = None
        external_dirs: list[Path] = []
    else:
        status = "done"
        project_root = volume.root / PROJECT_DIR_NAME
        disk_usage = shutil.disk_usage(volume.root)
        external_dirs = build_external_dirs(project_root)
        if volume.filesystem and volume.filesystem.upper() == "FAT32":
            warnings.append("Detected filesystem is FAT32, which has a 4 GB per-file size limit.")
        if disk_usage.free < 50 * 1_000_000_000:
            warnings.append("Free space is below 50 GB; validate capacity before downloading full datasets.")

    local_report = repo_root / "reports" / "STEP_0_environment_report.md"
    local_status = repo_root / "pipeline_status.json"
    generated_files = [local_report, local_status]

    if volume is not None and project_root is not None:
        external_report = project_root / "reports" / "STEP_0_environment_report.md"
        external_status = project_root / "pipeline_status.json"
        external_log = project_root / "logs" / "00_check_environment.log"
        config_path = repo_root / "configs" / "sen1floods11.yaml"
        generated_files.extend([external_report, external_status, external_log, config_path])

    if not args.dry_run and volume is not None and project_root is not None:
        for directory in external_dirs:
            directory.mkdir(parents=True, exist_ok=True)
        (repo_root / "reports").mkdir(parents=True, exist_ok=True)
        config_path = write_sen1_config(repo_root, project_root, volume.root)
    else:
        config_path = repo_root / "configs" / "sen1floods11.yaml"

    status_payload: dict[str, object] = {
        "current_step": 0,
        "status": status,
        "external_disk_label": DISK_LABEL,
        "external_disk_path": _format_path(volume.root) if volume else None,
        "external_project_root": _format_path(project_root) if project_root else None,
        "free_space_gb": _bytes_to_gb(disk_usage.free) if disk_usage else None,
        "free_space_gib": _bytes_to_gib(disk_usage.free) if disk_usage else None,
        "next_step_allowed": False,
        "generated_at": generated_at,
        "warnings": warnings,
    }

    report = build_report(
        status=status,
        generated_at=generated_at,
        repo_root=repo_root,
        volume=volume,
        project_root=project_root,
        created_dirs=external_dirs,
        generated_files=generated_files,
        python_info=python_info,
        pip_info=pip_info,
        conda_info=conda_info,
        disk_usage=disk_usage,
        warnings=warnings,
        dry_run=args.dry_run,
    )

    if not args.dry_run:
        local_report.parent.mkdir(parents=True, exist_ok=True)
        local_report.write_text(report, encoding="utf-8")
        write_json(local_status, status_payload)

        if volume is not None and project_root is not None:
            external_report.write_text(report, encoding="utf-8")
            write_json(external_status, status_payload)
            external_log.write_text(
                f"{generated_at} STEP 0 status={status} disk={_format_path(volume.root)}\n",
                encoding="utf-8",
            )

    print(json.dumps(status_payload, indent=2, ensure_ascii=True))
    return 0 if status == "done" else 2


if __name__ == "__main__":
    raise SystemExit(main())
